import React, { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Filter, ArrowUpDown, Eye } from 'lucide-react';

export default function Rankings({ candidatesList }) {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSkill, setSelectedSkill] = useState('All');
  const [sortBy, setSortBy] = useState('finalScore'); // finalScore, skillMatch, experience, growth, behavioral

  // Extract all unique skills across candidates for the filter dropdown
  const allSkills = useMemo(() => {
    const skillsSet = new Set();
    (candidatesList || []).forEach(c => (c.skills || []).forEach(s => skillsSet.add(s)));
    return ['All', ...Array.from(skillsSet)];
  }, [candidatesList]);

  // Filter and sort candidates
  const processedCandidates = useMemo(() => {
    return (candidatesList || [])
      .filter(candidate => {
        const nameVal = candidate.name || '';
        const roleVal = candidate.role || '';
        const matchesSearch = nameVal.toLowerCase().includes(searchTerm.toLowerCase()) ||
                              roleVal.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesSkill = selectedSkill === 'All' || (candidate.skills || []).includes(selectedSkill);
        return matchesSearch && matchesSkill;
      })
      .sort((a, b) => {
        if (sortBy === 'finalScore') {
          return b.finalScore - a.finalScore;
        } else {
          return b.scores[sortBy] - a.scores[sortBy];
        }
      });
  }, [searchTerm, selectedSkill, sortBy]);

  // Color mapper for statuses
  const getStatusStyle = (status) => {
    switch (status) {
      case 'Matched':
        return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
      case 'Interviewing':
        return 'bg-sky-500/10 text-sky-400 border-sky-500/20';
      case 'Under Review':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/20';
      case 'Rejected':
        return 'bg-rose-500/10 text-rose-400 border-rose-500/20';
      default:
        return 'bg-slate-500/10 text-slate-400 border-slate-500/20';
    }
  };

  // Score styling color
  const getScoreColor = (score) => {
    if (score >= 90) return 'text-emerald-400';
    if (score >= 80) return 'text-sky-400';
    if (score >= 70) return 'text-amber-400';
    return 'text-rose-400';
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Title */}
      <div>
        <h2 className="text-2xl font-bold text-white mb-2">Ranked Candidates</h2>
        <p className="text-slate-400 text-sm">
          Browse real-time candidate scores generated by extracting credentials and computing matching weights.
        </p>
      </div>

      {/* Control bar (Filters, Search, Sort) */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Search */}
        <div className="relative">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
          <input
            type="text"
            placeholder="Search by candidate name or role..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-[#1E293B] border border-slate-800 focus:border-sky-500/50 rounded-xl pl-10 pr-4 py-2.5 text-xs text-slate-200 outline-none transition-all duration-200"
          />
        </div>

        {/* Skill Filter */}
        <div className="relative">
          <Filter className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
          <select
            value={selectedSkill}
            onChange={(e) => setSelectedSkill(e.target.value)}
            className="w-full bg-[#1E293B] border border-slate-800 focus:border-sky-500/50 rounded-xl pl-10 pr-4 py-2.5 text-xs text-slate-300 outline-none appearance-none cursor-pointer transition-all duration-200"
          >
            {allSkills.map(skill => (
              <option key={skill} value={skill} className="bg-[#1E293B]">
                {skill === 'All' ? 'Filter by Skill: All' : `Skill: ${skill}`}
              </option>
            ))}
          </select>
        </div>

        {/* Sort select */}
        <div className="relative">
          <ArrowUpDown className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            className="w-full bg-[#1E293B] border border-slate-800 focus:border-sky-500/50 rounded-xl pl-10 pr-4 py-2.5 text-xs text-slate-300 outline-none appearance-none cursor-pointer transition-all duration-200"
          >
            <option value="finalScore" className="bg-[#1E293B]">Sort by: Final Score</option>
            <option value="skillMatch" className="bg-[#1E293B]">Sort by: Skill Match Score</option>
            <option value="experience" className="bg-[#1E293B]">Sort by: Experience Score</option>
            <option value="growth" className="bg-[#1E293B]">Sort by: Growth Score</option>
            <option value="behavioral" className="bg-[#1E293B]">Sort by: Behavioral Score</option>
          </select>
        </div>
      </div>

      {/* Candidates Table */}
      <div className="bg-[#1E293B] border border-slate-800 rounded-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800/80 bg-slate-900/10 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                <th className="px-6 py-4 w-16 text-center">Rank</th>
                <th className="px-6 py-4">Candidate Name</th>
                <th className="px-6 py-4 text-center">Final Score</th>
                <th className="px-6 py-4 text-center">Skill Match</th>
                <th className="px-6 py-4 text-center">Experience</th>
                <th className="px-6 py-4 text-center">Growth</th>
                <th className="px-6 py-4 text-center">Behavioral</th>
                <th className="px-6 py-4 text-center">Status</th>
                <th className="px-6 py-4 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-xs text-slate-300">
              {processedCandidates.length > 0 ? (
                processedCandidates.map((candidate) => (
                  <tr
                    key={candidate.id}
                    className="hover:bg-slate-800/40 transition-colors duration-150 group"
                  >
                    {/* Rank */}
                    <td className="px-6 py-4.5 font-bold text-center text-slate-400">
                      {candidate.rank === 1 ? (
                        <span className="inline-flex items-center justify-center h-6 w-6 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-500">
                          1
                        </span>
                      ) : candidate.rank === 2 ? (
                        <span className="inline-flex items-center justify-center h-6 w-6 rounded-full bg-slate-400/10 border border-slate-400/30 text-slate-300">
                          2
                        </span>
                      ) : (
                        candidate.rank
                      )}
                    </td>

                    {/* Candidate Name & Role */}
                    <td className="px-6 py-4.5">
                      <div>
                        <p className="font-semibold text-slate-200 group-hover:text-sky-400 transition-colors duration-150">
                          {candidate.name}
                        </p>
                        <p className="text-[10px] text-slate-500 mt-0.5">{candidate.role}</p>
                      </div>
                    </td>

                    {/* Final Score */}
                    <td className="px-6 py-4.5 text-center font-bold">
                      <span className={`px-2 py-1 rounded-lg bg-slate-900/40 border border-slate-800 ${getScoreColor(candidate.finalScore)}`}>
                        {candidate.finalScore}%
                      </span>
                    </td>

                    {/* Scores breakdowns — show '—' when not returned by API */}
                    <td className="px-6 py-4.5 text-center font-medium text-slate-400">
                      {candidate.scores?.skillMatch != null ? `${candidate.scores.skillMatch}%` : <span className="text-slate-600">—</span>}
                    </td>
                    <td className="px-6 py-4.5 text-center font-medium text-slate-400">
                      {candidate.scores?.experience != null ? `${candidate.scores.experience}%` : <span className="text-slate-600">—</span>}
                    </td>
                    <td className="px-6 py-4.5 text-center font-medium text-slate-400">
                      {candidate.scores?.growth != null ? `${candidate.scores.growth}%` : <span className="text-slate-600">—</span>}
                    </td>
                    <td className="px-6 py-4.5 text-center font-medium text-slate-400">
                      {candidate.scores?.behavioral != null ? `${candidate.scores.behavioral}%` : <span className="text-slate-600">—</span>}
                    </td>

                    {/* Status */}
                    <td className="px-6 py-4.5 text-center">
                      <span className={`inline-block px-2.5 py-0.5 rounded-full border text-[10px] font-semibold ${getStatusStyle(candidate.status)}`}>
                        {candidate.status}
                      </span>
                    </td>

                    {/* Action */}
                    <td className="px-6 py-4.5 text-center">
                      <button
                        onClick={() => navigate(`/candidate/${candidate.id}`)}
                        className="p-2 text-slate-400 hover:text-sky-400 hover:bg-sky-500/10 rounded-lg transition-all duration-200"
                        title="View profile"
                      >
                        <Eye className="h-4 w-4" />
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="9" className="px-6 py-12 text-center text-slate-500">
                    No candidates match the selected filters.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
